version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - echo install process started
      - if [ -z "${BRANCH}" ]; then echo "BRANCH not set" && exit 1 ; fi
      - if [ -z "${ENVIRONMENT}" ]; then echo "ENVIRONMENT not set" && exit 1 ; fi
      - npm install && npm install -g @angular/cli
  build:
    commands:
      - echo "Building project"
      - npm run build
  # post_build:
  #   commands:
  #     - ls -ll
  #     - ls -ll dist/ng-cv/
artifacts:
  files:
    - '**/*'
  base-directory: 'dist/ng-cv/'
