version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm ci
  #pre_build:
    #commands:
      # - echo "I don't need pre_build commands"
      # - command
  build:
    commands:
      - echo "Building project"
      - npm run build
  # post_build:
  #   commands:
  #     - ls -ll
  #     - ls -ll dist/ng-cv/
artifacts:
  files:
    - '**/*'
  base-directory: 'dist/ng-cv/'
